logging:
    level: INFO
    file_path: logs/threat_detector.log

database:
    path: security.db

thresholds:
    max_failed_attempts: 5
    suspicious_ports:
        - 22
        - 3389
        - 445
    max_connections: 50

threat_intelligence:
    api_url: https://threatintel.example.com
