logging:
    level: INFO
    file_path: logs/threat_detector.log


database:
    path: threat_detection.db

thresholds:
    max_failed_attempts: 5 
    suspicious_ports:
        - 22    # SSH
        - 3389  # RDP
        - 445   # SMB 
    max_connections: 50
